### ISSUE TITLE
ToDo: Create a server script to reset the database

### ISSUE THREAD

**Issue by mindstorm8191** [mindstorm8191/settlerswarlords#4]
With testing going on with the game, as well as exporting the database to file, we need a way to reset the database. It is easy enough to truncate the player, map, building etc tables, but the item table and itemGroup tables pose a more difficult problem: some of these records relate to building types and the data related to it.

We need to set up a script that can clear out the database, without deleting critical structureType portions.

**Comment by geeksesi** [comment]
hi,
i can do it.
but please don't make react app by default react config. that's have a bad config.

for database.
we need first a migration.
i will setup it. i will change your server file please don't change that for not conflict.

**Comment by geeksesi** [comment]
i can make migration from your sql file exist.
if you have some default value or want another database struct please tell here i will start after your answer :) 

also we can talk in discord (or telegram )about this game 
tg : @geeksesi_javad
discord : geeksesi_javad#3600

**Comment by mindstorm8191** [comment]
With the Actions working correctly now (well, one of them is functional), there is now a new table to handle items related to structures. This means that exporting and resetting the database can be done easily via phpMyAdmin.

This script will no longer be needed. At least not right now; maybe later it will be.
